### PR TITLE
optimized last_element

### PR DESCRIPTION
**Pull request by jonathanpoelen**
/usr/bin/time --format="%Es  %Mk" g++-5

```cpp
#include <brigand/sequences/back.hpp>
#include <brigand/sequences/list.hpp>
#include <brigand/sequences/make_sequence.hpp>
#include <brigand/types/integer.hpp>

template<class T> using void_t = T;

template<int N>
constexpr bool test_last_element()
{
  using list = brigand::push_back<brigand::make_sequence<brigand::size_t<0>, N>, int>;
  return brigand::back<list>(1);
}

static_assert(test_last_element<1>(), "");
static_assert(test_last_element<10>(), "");
static_assert(test_last_element<100>(), "");
static_assert(test_last_element<500>(), "");
static_assert(test_last_element<600>(), "");
static_assert(test_last_element<700>(), "");
static_assert(test_last_element<800>(), "");
static_assert(test_last_element<850>(), "");
//old: 0:00.80s  196232k
//new: 0:00.64s  156096k

static_assert(test_last_element<900>(), "");
static_assert(test_last_element<1000>(), "");
static_assert(test_last_element<2000>(), "");
static_assert(test_last_element<3000>(), "");
//old: 0:05.70s  1009680k
//new: 0:03.85s  774852k
```

### CODE REVIEW

**Comment by edouarda** [comment]
MSVC 2013 doesn't like it! :-)

**Comment by porkybrain** [comment]
MSVC2013 has problems with templated aliases sometimes. 

This should work though:

```C++
		template<class> 
		struct voidp{
			using type = void const *;
		};

		template<class T, class... Ts>
		struct last_element
		{
			template<class Us>
			static Us last(typename voidp<Ts>::type..., Us*);

			using type = decltype(last(nullptr, static_cast<Ts*>(nullptr)...));
		};
```

**Comment by porkybrain** [comment]
actually since we already have an optimized `at` why not just use that?

**Comment by jonathanpoelen** [comment]
I did not think about it :)

After trying with `brigand::at_c<list, N>`, I get:
- 0:01.69s  329400k
- 0:09.14s  1656948k.

Much slower than a specialized version. I will work on improving `at_c` before resuming `last_element`.

**Comment by jfalcou** [comment]
last_element could be sooo simple if decltype(declval<T>()...)  was allowed :(

**Comment by jonathanpoelen** [comment]
moved in #131

**Pull request closed without merging**
