### PR TITLE
Fix #85 - Implements bitwise operators

### LINKED ISSUE #85: Implemnts bitwise operator
- [ ] bitand_
 - [ ] bitor_
 - [ ] bitxor_
 - [ ] shift_left
 - [ ] shift_right

### PR DESCRIPTION
**Pull request by jonathanpoelen**
- [x] bitand_
- [x] bitor_
- [x] bitxor_
- [x] shift_left
- [x] shift_right

### CODE REVIEW

**Comment by edouarda** [comment]
All of this is already implemented but thanks.
________________________________
De : Jonathan Poelen<mailto:notifications@github.com>
Envoyé : ‎04/‎10/‎2015 01:17
À : edouarda/brigand<mailto:brigand@noreply.github.com>
Objet : [brigand] Fix #85 - Implements bitwise operators (#89)


  *    bitand_
  *    bitor_
  *    bitxor_
  *    shift_left
  *    shift_right

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/edouarda/brigand/pull/89

Commit Summary

  *   Fix #85 - Implements bitwise operators: bitand_, bitor_, bitxor_, shift_left and shift_right

File Changes

  *   M CMakeLists.txt<https://github.com/edouarda/brigand/pull/89/files#diff-0> (11)
  *   M brigand/functions.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-1> (1)
  *   A brigand/functions/bitwise.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-2> (13)
  *   A brigand/functions/bitwise/bitand.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-3> (15)
  *   A brigand/functions/bitwise/bitor.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-4> (15)
  *   A brigand/functions/bitwise/bitxor.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-5> (15)
  *   A brigand/functions/bitwise/shift_left.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-6> (15)
  *   A brigand/functions/bitwise/shift_right.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-7> (15)
  *   A test/bitwise_test.cpp<https://github.com/edouarda/brigand/pull/89/files#diff-8> (27)

Patch Links:

  *   https://github.com/edouarda/brigand/pull/89.patch
  *   https://github.com/edouarda/brigand/pull/89.diff

**Comment by edouarda** [comment]
I will be back home tonight let me sort all of this next week.
________________________________
De : Jonathan Poelen<mailto:notifications@github.com>
Envoyé : ‎04/‎10/‎2015 01:17
À : edouarda/brigand<mailto:brigand@noreply.github.com>
Objet : [brigand] Fix #85 - Implements bitwise operators (#89)


  *    bitand_
  *    bitor_
  *    bitxor_
  *    shift_left
  *    shift_right

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/edouarda/brigand/pull/89

Commit Summary

  *   Fix #85 - Implements bitwise operators: bitand_, bitor_, bitxor_, shift_left and shift_right

File Changes

  *   M CMakeLists.txt<https://github.com/edouarda/brigand/pull/89/files#diff-0> (11)
  *   M brigand/functions.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-1> (1)
  *   A brigand/functions/bitwise.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-2> (13)
  *   A brigand/functions/bitwise/bitand.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-3> (15)
  *   A brigand/functions/bitwise/bitor.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-4> (15)
  *   A brigand/functions/bitwise/bitxor.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-5> (15)
  *   A brigand/functions/bitwise/shift_left.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-6> (15)
  *   A brigand/functions/bitwise/shift_right.hpp<https://github.com/edouarda/brigand/pull/89/files#diff-7> (15)
  *   A test/bitwise_test.cpp<https://github.com/edouarda/brigand/pull/89/files#diff-8> (27)

Patch Links:

  *   https://github.com/edouarda/brigand/pull/89.patch
  *   https://github.com/edouarda/brigand/pull/89.diff

**Comment by jonathanpoelen** [comment]
ok :')

**Comment by jfalcou** [comment]
@jonathanpoelen  as we soemtimes start doign thing and not inishing it fast, it could be cool if you send us an email to say "hey I saw issue #N, i'm takign a shot at it" so we can actually assign it to you and we cna move onto something else :)

Thanks for your effort anyway :D

**Comment by jonathanpoelen** [comment]
ok, I will do it.

**Pull request closed without merging**
