### PR TITLE
added Debian packaging support

### PR DESCRIPTION
**Pull request by chybz**
Dear fellow C++ ninjas,

I thought you might be interested in some Debian packaging support for your library.
While files in `debian/` are plain static and won't change your typical use, I had to modify `CMakeLists.txt` for "proper" packaging. This might not be desirable for you.

Cheers.

### CODE REVIEW

**Comment by jfalcou** [comment]
my one question is how does this interacts with using brigand CMake on windows ? 
Can't the specific calls in the main CMakeLists.txt be protected somehow to only kicks in when on Debian ?

**Comment by edouarda** [comment]
The email is incorrect and I certainly don't want my valid email to be out anyway. :-)

**Comment by chybz** [comment]
@jfalcou the `libbrigand.pc` can be used under Windows as well (we use it here) and within other projects via CMake's PkgConfig module. Regarding the change of `DESTINATION` within the `install` commands, I tried to follow common practice (i.e.: install different kinds of things into separate directories). I perfectly understand you don't want your habits changed, though.
@edouarda Feel free to give me a valid email :]

Please tell me if the packaging support is of no interest for you, otherwise I'll update my branch with what best suits you.

**Comment by pfultz2** [comment]
> Regarding the change of DESTINATION within the install commands, I tried to follow common practice

Yea, header files should always go to the include directory by default.

**Comment by jfalcou** [comment]
I think we want this kind of support as it helps discoverability of the tools outside the regular C++ spelunkers.  What are the details you miss ?

**Comment by jfalcou** [comment]
Use the 

brigand-dev@googlegroups.com

email and we'll merge this

**Comment by edouarda** [comment]
Just merged it manually and fixed the e-mail.

**Pull request closed without merging**
