### PR TITLE
added split

### PR DESCRIPTION
**Pull request by porkybrain**
this one is simple and recursive, we can make it faster later

### CODE REVIEW

**Comment by jfalcou** [comment]
could we get a squashed version of this ? Code looks OK, I'm just OCD about exploratory commit being visible :p

**Comment by edouarda** [comment]
I can squash it.

**Comment by porkybrain** [comment]
@jfalcou yeah sorry about the spamming ;) guessing about what MSVC2013 supports turned out to be a stupid idea

**Comment by edouarda** [comment]
When 2015 will be more wide spread we will drop support for 2013 but right now I think we need it.

**Comment by edouarda** [comment]
If I squash it your name will disapear from the contribution, maybe you want to do a squashed PR instead?

**Comment by porkybrain** [comment]
hehe I don't really care about my name being on stuff, I just want there to be more good code. I also plan on contributing to this repo in the future so eventually I will show up ;)

**Comment by edouarda** [comment]
Done! :-)

**Pull request closed without merging**
