### PR TITLE
Start adding documentation

### PR DESCRIPTION
**Pull request by nilsdeppe**
The goal of this PR is to have somewhere we can look at code and documentation and decide how we want things to look, not to be merged immediately. Basically, I think the discussion will be much more productive if we have working examples to look at.

All I've done here is taken the main documentation from the wiki and moved it into Markdown files that Doxygen compiles. How to handle this within Standardese is an open question I haven't tried to answer. My main question for feedback is that I've added a target library to CMake called `example` which will compile the code snippets shown in the documentation. I haven't yet moved all the code snippets over because I wanted to get feedback before doing all of it. If you look at `introduction.md` you'll notice the `\snippet tutorials/introduction.cpp DOXYGEN_TAG` lines. These pull in the snippets from the C++ file. I think there is a lot to be said for having examples that are actually tested by CI. That way as any code is changed the required changes to the examples will be made, and hopefully the text explaining the examples too. Any objections to doing it this way?

Second, if we do have all the examples compiled, I'm not sure we should have the `#include`s in them. I think having people include the `brigand.hpp` file is the best way to go. The primary motivation here is that otherwise we would really need one C++ file for each example to test the headers being included are correct. Having hundreds of C++ files I think will be too burdensome given that it could be avoided quite easily. Thoughts on this?

Third, I was planning to rework the order of the documentation and add a fairly extensive "intro to TMP" section. A good introduction to the different concepts and how one should think about things at compile time is something I found was hard to find (I couldn't find anything, but the internet is vast), so I think having an intro to TMP would be very valuable. It would probably also give us another advantage in the Boost submission process.

I want to get the ball rolling on how we want things documented since I've started adding continuations and will be documenting that as I go.

### CODE REVIEW

**Comment by odinthenerd** [comment]
@foonathan how do we include markdown files in standardese?

**Comment by foonathan** [comment]
You simply write them as normal. There is a special template markup syntax you can use to replace parts of  it with standardese generated content.

**Comment by nilsdeppe** [comment]
Okay, so I'm able to have it parse and effectively copy the `.md` files. Are there plans for Standardese to produce html output from the md files similar to Doxygen? Supporting the `{#link_name}` syntax would also be nice to have. I guess the question is ultimately should Standardese produce a full webpage like Doxygen does, or parse and generate the C++ documentation?

**Comment by foonathan** [comment]
I'm currently redoing a lot of standardese, it will be able to generate a full page then.

Links in markdown are supported but syntax is different.

**Comment by nilsdeppe** [comment]
Ah great! I saw you mention a lot of changes in one of the issues. I don't think different syntax for the md links will be bad, though likely supporting Doxygen syntax wherever it doesn't result in having to adopt some of the weird behavior of Doxygen is a good thing for better user adoption. Though I think for Brigand at least the syntax is pretty much irrelevant as long as the functionality is there :)

**Comment by odinthenerd** [comment]
my 2 cents is we should concentrate on standardese even if its volatile since its the future ;)

**Comment by nilsdeppe** [comment]
Sounds good to me. Probably a lot of mutual benefit to be had :)

So that leaves us with the other points of interest. 

1) Should all examples be compiled by CI and then include using `\snippet`? @foonathan [said](https://github.com/foonathan/standardese/issues/56) he's working on supporting something like `\snippet` in the future

2) For examples I think we should assume inclusion of `<brigand/brigand.hpp>` rather than specifying individual headers to include.

3) Rework wiki documentation to add a more pedagogical flow taking people from basic use of templates to actually using Brigand. This is something I was looking for when I started.

**Comment by odinthenerd** [comment]
1 no idea, someone else should decide this
2 sounds good to me
3 I very much agree with this, I think most advanced TMP people do but none have the time

**Comment by edouarda** [comment]
From experience it's better to compile the examples, this is the best way to make sure the examples are up to date.

If it's faster I guess you can include the behemot header brigand.hpp

Do you have a suggestion for a better documentation flow?

**Comment by nilsdeppe** [comment]
Okay, so I will use the `\snippet` command to add some pressure to @foonathan to support it (or some similar implementation) in Standardese ;)

It doesn't seem to slow down compilation (at least not that I can notice) to include `brigand.hpp` vs. the individual ones. Since we will be compiling much fewer files I think it'll be faster to compile the code with including the `brigand.hpp` file. Including the single file makes the examples easier to maintain, which I think is worth a lot.

I've been thinking about and working on this a bit. I think adding a section before `Introduction` that goes over compile time data structures, accessing a type list, and a map. Next I was thinking going over in detail the different types of metafunctions there are presenting minimal motivation to choose one over the other. Then I think algorithms would be a good next choice. After algorithms we could look at giving advice about "for loops" that don't fit into the existing algorithms, etc.

**Comment by edouarda** [comment]
Shall I close this PR? :)

**Comment by nilsdeppe** [comment]
Yes, let's close this. I'll have to clean up what I've done so far and put in a new PR :)

**Comment by edouarda** [comment]
Great looking forward to reading it!

**Pull request closed without merging**
