### PR TITLE
Duplicate in map

### PR DESCRIPTION
**Pull request by jonathanpoelen**
#26

### CODE REVIEW

**Comment by edouarda** [comment]
This is very elegant, do you think it would be possible to have a more explicit message than "type is already a base"? If you see my branch issue29 I've done something with static asserts, the problem is that on VS the static assertions are triggered only when instantiating the type. :/

**Comment by jonathanpoelen** [comment]
Sorry for the error message, but it is not possible to check if an inheritance is valid or not. :'(

I do not have VS, difficult for me to test, but used an internal type can it trigger the assert? `using map = typename map_impl<T ...>::self` with `using self = map_impl`.

**Comment by edouarda** [comment]
Nope. I'll merge your pull request, at least we get a compilation failure. What do you think @jfalcou ?

**Comment by jfalcou** [comment]
the message can be made clearer by adding a small comments near the check_unique_keys that say "if you got this and this error it means ..."

**Pull request merged**
