### PR TITLE
added filter and made some algorithms faster

### PR DESCRIPTION
**Pull request by porkybrain**

### CODE REVIEW

**Comment by porkybrain** [comment]
damn it MSVC sucks at constexpr

**Comment by edouarda** [comment]
Yes it does :-)

**Comment by porkybrain** [comment]
finally, that was not fun, plus it was only like 50% microsoft stupidity, the rest was mine!

**Comment by porkybrain** [comment]
I have the fast version with constexpr run when #ifdef __GNUC__ , that should keep it from running on MSVC.

**Comment by edouarda** [comment]
Please use our macros instead: https://github.com/edouarda/brigand/blob/master/brigand/config.hpp

**Comment by porkybrain** [comment]
ok now im happy with it. Should rule metabench by a good margin ;)

**Pull request merged**
