### PR TITLE
added universal lambda fast track to find

### PR DESCRIPTION
**Pull request by porkybrain**

### CODE REVIEW

**Comment by porkybrain** [comment]
finally, damn MSVC

**Comment by edouarda** [comment]
What's the difference in speed?

**Comment by porkybrain** [comment]
find is only about 5% faster with the fast track, find is not as much about lambda speed as other algorithms though, replace_if was 25% faster or so but with MSVC not liking the syntax and the MSVC detection apparently not working right (or me being stupid?) I had to add the extra instantiation (replacer) which leaves it about 5% faster as well. I think we are kind of getting into the law of diminishing returns here for most algorithms. Without the `replacer` work around `boost::mp_replace_if<l,is_last, int>` from @pdimov library is essentially exactly the same speed as the brigand equivalent (on clang 3.7 and on my machine of course). 

I think there still is lots of potential in the more complex algorithms like sort but as far as the simple ones go adopting the "universal lambda fasttrack pattern" will probably get us within a few percent of mp11 most of the time.

**Comment by porkybrain** [comment]
transforming 25 unique lists of 500 unique integral_constant `brigand::transform<L, brigand::bind<std::add_pointer_t,_1>>;` is actually faster than `boost::mp_transform<std::add_pointer_t, L>` on most runs (and within the margin of error) on my machine and twice as fast as meta. Can't wait for my pull request to metabench to go live so we can see the results there.

**Comment by porkybrain** [comment]
Thats why I'm here ;)  compounded compilation speed leads to better C++ libraries leads to more C++ usage = less java = probably more CO2 savings than all the green washing and clueless do-gooders combined. I've never felt so much like an Eco-warrier ;)

**Pull request merged**
