### PR TITLE
optimized find

### PR DESCRIPTION
**Pull request by porkybrain**

### CODE REVIEW

**Comment by ldionne** [comment]
This brings the issue that if evaluating the predicate on some element causes a hard error, this implementation may trigger a hard error even if the searched element is found before. For example

```c++
struct invalid;

struct predicate {
    template <typename I>
    struct apply : I { };
};

using list = brigand::list<
    std::false_type, std::true_type,
    invalid, invalid, invalid, invalid, invalid, invalid, invalid,
    invalid, invalid, invalid, invalid, invalid, invalid, invalid,
    invalid, invalid
>;

using Fail = brigand::find<list, predicate>;
```

This should fail because `predicate::apply<invalid>` will be evaluated even though it should never be, cause `predicate::apply<std::true_type>` should stop the search. This is probably just an academic issue, but still one that I thought was worth pointing out.

**Comment by edouarda** [comment]
I think it is interesting. What you are saying, is that the current implementation of find requires the predicate to work on all the elements of the list, whereas it would be better if find returns successfully even if the predicate doesn't make sense for some elements of the list and it can find something before it reaches those elements.

**Comment by porkybrain** [comment]
Interesting issue, seems like playing with fire though to find in a list with a pred which does not accept all elements. I guess the use case would be a SFINAE context.

**Comment by ldionne** [comment]
What I'm really saying is that you should be aware of this particularity of the new implementation. FWIW, I would have very little sympathy for someone that would use `find` with a predicate that fails for some elements, but w/e.

**Comment by edouarda** [comment]
Yes because you can still filter the invalid elements before doing the find.

**Pull request merged**
