### PR TITLE
Add keys_as_sequence and values_as_sequence

### PR DESCRIPTION
**Pull request by mkurdej**
Add `map_keys_list<Map, Sequence = set>`, `map_values_list<Map, Sequence = list>` that returns a Sequence of keys/values of a map.

These are convience functions.
I've added as well `as_sequence<L, Sequence>` that is a generalisation of `as_list<L> = as_sequence<L, list>`.

Names to be discussed.

### CODE REVIEW

**Comment by edouarda** [comment]
Cool feature, but I think ```map_keys_list ```  isn't a good name.

What about keys_sequence and values_sequence ?

**Comment by mkurdej** [comment]
`keys_as_sequence`, `values_as_sequence` - I like these.

Where should these files reside? For the moment they are in `sequences/` together with `map.hpp`. Should they be in `algorithms/`? Or in `convenience/`? Any ideas?

**Comment by edouarda** [comment]
They should be in sequences.

**Comment by mkurdej** [comment]
I've squashed the commits. Are you ok to merge it?

**Pull request merged**
