### PR TITLE
Support adaptation to boost::fusion

### PR DESCRIPTION
**Pull request by jfalcou**
This may requires appveyor to use Boost install for proper testting.

### CODE REVIEW

**Comment by edouarda** [comment]
How can we do that?

**Comment by jfalcou** [comment]
Apparently, appveyor has an "Unstable" image in which Bosot is supposedly preinstalled somewhere. You then pass this somewhere using the environment variable settings. I tried that for boost.dispatch but it didn't work. My windows-fu is maybe too weak.

**Comment by jfalcou** [comment]
see : http://help.appveyor.com/discussions/questions/455-boost-lib-depency#comment_34924423

**Comment by edouarda** [comment]
I will have a look. Had to reinstall my computer. :x

**Comment by jfalcou** [comment]
Apparently adding -DBOOST_ROOT="C:\Libraries\boost_1_59_0" to the cmake command is enough now to get boost on appveyor

**Comment by edouarda** [comment]
Duly noted, will try today.

**Comment by edouarda** [comment]
Done! Available in master.

**Pull request merged**
