### PR TITLE
optimized sort

### PR DESCRIPTION
**Pull request by porkybrain**

### CODE REVIEW

**Comment by porkybrain** [comment]
Ok downloading MSVC2013 (damn thing)

**Comment by edouarda** [comment]
It might not be possible to make it work. In which case a define is acceptable.

**Comment by porkybrain** [comment]
Finally! I think given the complexity of the new sort we should write some more unit tests just to be sure I handled all possible scenarios and nothing is ambiguous. But using this in a real project which sorts like 100 lists of different sizes I didn't see anything.

**Comment by porkybrain** [comment]
hold on don't merge yet. I may have found a bug.

**Comment by porkybrain** [comment]
Ok I can't find anything else so looks good to me now.

**Comment by mkurdej** [comment]
Looks really nice!

BTW, I may be a bit picky, but may you have a pass of clang-format over your changes, please? There is already .clang-format config file.

**Pull request merged**
