### PR TITLE
Added `filter` algorithm

### PR DESCRIPTION
**Pull request by dodheim**
I needed filtering functionality for myself and decided to contribute it back, but I'm not sure of the protocol here. I've added only a single, silly test along with the implementation; please let me know if anything else is needed.

Regards,

### CODE REVIEW

**Comment by dodheim** [comment]
I should add that I've only tested this with MSVC 2015.

**Comment by edouarda** [comment]
Any contribution is welcome, but just make sure all builds pass... And yours doesn't on VS 2013.

**Comment by dodheim** [comment]
I apologize, I don't have MSVC 2013 to test with, only 2015. Given that the code works given a sufficiently recent toolset, the code seems to have merit, but I don't know what guards are appropriate, etc.

**Comment by edouarda** [comment]
As you can see we have continuous integration, when it doesn't pass PR aren't accepted. We want to support the latest two versions of VS, VS 2015 is still bleeding edge.

**Comment by edouarda** [comment]
I will have a look at your error when I have the time. Maybe you can see what confuses VS 2013 quickly? 

[https://ci.appveyor.com/project/edouarda/brigand/build/1.0.52]

**Comment by mkurdej** [comment]
Just a stupid question, wouldn't it be better and easier to implement `filter` in terms of `remove`?
One just has to negate the predicate with `brigand::not_` and it's done, nope?

**Comment by edouarda** [comment]
Feel free to submit again later or to open an issue describing your problem. I will close this pull request for the moment.

**Pull request closed without merging**
