### PR TITLE
Add partition and sort algorithms (+ unit tests)

### PR DESCRIPTION
**Pull request by ccharly**
hey there! @jfalcou told me that `partition` and `sort` were missing and I wanted to give it a try using `brigand`! :)

I've not tried to compile them using MSVC since I don't have a working machine for that, but I will be able to do so on Monday.

### CODE REVIEW

**Comment by ccharly** [comment]
Does someone know how to fix this? I'm currently installing windows stuffs to debug it, but if anyone has any clue about what is happening with MSVC it could help me a lot! :)

**Comment by edouarda** [comment]
Difficult to say without checking out your branch. It can be something very trivial like VS just needing some intermediary type or something nasty like VS not supporting advanced template aliasing (I had this problem with set).

**Comment by ccharly** [comment]
According to the CI there is an internal compiler error... So it is quite hard to debug ;). I'll try to add intermediate types. Also, when you talk about advanced template aliasing, you mean stuff like `template <...> using foo = ....`?

**Comment by edouarda** [comment]
Have a look at what I merged. VS really hates when you do something like using boom = bam; and bam is in the form of a template.

**Comment by ccharly** [comment]
I'll have a look when I'll have time to do that. :) Thanks for the tip!

**Pull request closed without merging**
